// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
///
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBoSospzEHzvMCUwFhzts4Tpc60FXdmCbQ',
    appId: '1:590720697179:android:591118c5a7ae15615b907e',
    messagingSenderId: '590720697179',
    projectId: 'dhanda-studio',
    databaseURL:
        'https://dhanda-studio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dhanda-studio.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCTy6FTe_Y6WwfOJANy_hnrOoN8ZQIDSj4',
    appId: '1:590720697179:ios:7fd92ee3321f59b35b907e',
    messagingSenderId: '590720697179',
    projectId: 'dhanda-studio',
    databaseURL:
        'https://dhanda-studio-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'dhanda-studio.appspot.com',
    iosClientId:
        '590720697179-t2nv1acfd59u861o4366j3bceit596c5.apps.googleusercontent.com',
    iosBundleId: 'biz.dhanda.dhandaApp',
  );
}
